-- ===========================================================================
-- spec/helpers/wow.lua  ·  headless stand-in for the WoW client API.
--
-- Installs the globals the addon reads into _G, backed by state the tests can
-- drive: a manual clock (no real waiting), an event bus, a settable player
-- position/facing, and recorders for the things we assert on (spoken text,
-- played sounds, chat output).
--
-- Frames auto-stub any method we haven't modelled (see `stubbed` below), so a
-- new UI call in the addon never fails the suite for the wrong reason. The
-- methods the tests actually observe -- visibility, text, colour, scripts,
-- events -- are implemented for real and keep state.
-- ===========================================================================

local M = {}

-- ---------------------------------------------------------------------------
-- Secret values
--
-- Retail can hand back "secret" values from position/unit APIs. They tolerate
-- being passed around but throw the moment you do arithmetic or compare them,
-- which is exactly what the addon's pcall guards exist to survive. Modelling
-- that faithfully is the only way to test those guards.
-- ---------------------------------------------------------------------------

local function boom()
	error("attempt to use a secret value", 2)
end

local secretmt = {
	__add = boom, __sub = boom, __mul = boom, __div = boom, __mod = boom,
	__pow = boom, __unm = boom, __concat = boom, __len = boom,
	__lt = boom, __le = boom, __tostring = boom,
	__index = boom, __newindex = boom,
}

-- Wrap `v` so any arithmetic/comparison on it errors, like a real secret value.
function M.secret(v)
	return setmetatable({ __secret = true, __value = v }, secretmt)
end

local function isSecret(v)
	return type(v) == "table" and rawget(v, "__secret") == true
end

-- For the tests: did this value survive as the secret the client gave us?
M.isSecret = isSecret

-- ---------------------------------------------------------------------------
-- State (rebuilt by M.reset)
-- ---------------------------------------------------------------------------

local clock          -- seconds; only M.advance moves it
local timers         -- pending C_Timer entries
local listeners      -- event -> { frame, ... }
local allFrames      -- every frame created, for OnUpdate driving

M.spoken = {}        -- { {voiceID, text, rate, volume, overlap}, ... }
M.sounds = {}        -- { soundFileOrKit, ... }
M.chat = {}          -- printed lines
M.bindings = {}      -- command -> key
M.popups = {}        -- shown StaticPopup names

M.position = nil     -- { a, b, z, instanceID } or nil for "unavailable"
M.facing = 0
M.instanceMapID = 0
M.zoneText = ""
M.uiMapID = 0
M.hostile = {}       -- unit token -> bool
M.guids = {}         -- unit token -> GUID string
M.auras = {}         -- unit token -> { {name, duration, expirationTime, filter}, ... }
M.casts = {}         -- unit token -> { spellID, startMS, endMS } or nil
M.channels = {}      -- unit token -> { spellID, name, startMS, endMS } or nil

-- Retail refuses the aura API outright to a tainted caller in some content:
-- not "no auras", but an error out of the call itself.
M.aurasBlocked = false

-- ---------------------------------------------------------------------------
-- Frames
-- ---------------------------------------------------------------------------

-- Methods that exist only so the addon's UI code runs; they do nothing and
-- return the frame so chained calls keep working.
local stubbed = {
	"SetSize", "SetWidth", "SetHeight", "SetAllPoints", "ClearAllPoints",
	"SetMovable", "SetResizable", "SetClampedToScreen",
	"SetToplevel", "StartMoving", "StopMovingOrSizing",
	"EnableKeyboard", "SetPropagateKeyboardInput", "SetUserPlaced", "EnableMouseWheel",
	"RegisterForDrag", "RegisterForClicks", "SetHitRectInsets", "SetClipsChildren",
	"SetHighlightTexture", "SetNormalTexture", "SetPushedTexture", "SetDisabledTexture",
	"SetBackdrop", "SetBackdropColor", "SetBackdropBorderColor",
	"SetTexture", "SetAtlas", "SetTexCoord", "SetColorTexture",
	"SetDrawLayer", "SetBlendMode", "SetDesaturated", "SetGradient", "SetMask",
	"SetJustifyH", "SetJustifyV", "SetShadowOffset", "SetShadowColor",
	"SetFont", "SetSpacing", "SetWordWrap", "SetNonSpaceWrap", "SetMaxLines",
	"SetMinMaxValues", "SetValueStep", "SetObeyStepOnDrag", "SetOrientation",
	"SetAlpha", "SetIgnoreParentScale", "SetIgnoreParentAlpha",
	"SetParent", "Raise", "Lower", "SetID",
	"Click", "LockHighlight", "UnlockHighlight",
	-- The 11.0 dropdown. Its menu is generated by the client when the player
	-- opens it, which never happens headlessly, so the generator these are handed
	-- is deliberately not run: what the options page is asked to prove here is
	-- that it builds and refreshes, not what the menu would contain.
	"SetupMenu", "GenerateMenu", "SetDefaultText", "SetSelectionText", "OverrideText",
}

local frameProto = {}
frameProto.__index = frameProto

for _, name in ipairs(stubbed) do
	frameProto[name] = function(self) return self end
end

-- Stacking order and mouse input, remembered rather than discarded: `/ss status`
-- reports them so a click that goes nowhere in the field can be told apart from
-- a click handler that is wrong.
function frameProto:SetFrameStrata(s) self._strata = s return self end
function frameProto:GetFrameStrata() return self._strata or "MEDIUM" end
function frameProto:SetFrameLevel(n) self._level = n return self end
function frameProto:GetFrameLevel() return self._level or 1 end
function frameProto:EnableMouse(v) self._mouse = v ~= false return self end
function frameProto:IsMouseEnabled() return self._mouse ~= false end

-- Attributes are remembered, not discarded: the chat macros the press buttons
-- carry live here, and whether they were installed is the whole question.
function frameProto:SetAttribute(k, v)
	self._attrs = self._attrs or {}
	self._attrs[k] = v
	return self
end
function frameProto:GetAttribute(k)
	return self._attrs and self._attrs[k] or nil
end

function frameProto:Show() self._shown = true end
function frameProto:Hide() self._shown = false end
function frameProto:IsShown() return self._shown and true or false end
function frameProto:IsVisible() return self._shown and true or false end
function frameProto:SetShown(v) self._shown = v and true or false end

function frameProto:SetText(t) self._text = t end

-- The client formats secret values in C and never hands them back, which is the
-- only way a secret can be put on screen at all. Modelled faithfully: a secret
-- argument is kept exactly as it arrived and never concatenated, because
-- concatenating one is what throws.
function frameProto:SetFormattedText(fmt, ...)
	local args = { ... }
	self._format = fmt
	for _, v in ipairs(args) do
		if isSecret(v) then
			self._formatArgs = args
			self._text = nil
			return self
		end
	end
	self._formatArgs = args
	local ok, out = pcall(string.format, fmt, ...)
	self._text = ok and out or fmt
	return self
end
function frameProto:GetText() return self._text end
function frameProto:GetStringWidth() return #tostring(self._text or "") * 6 end
function frameProto:GetFont() return "Fonts\\FRIZQT__.TTF", 12, "" end

function frameProto:SetTextColor(r, g, b, a) self._textColor = { r, g, b, a } end
function frameProto:GetTextColor()
	local c = self._textColor or { 1, 1, 1, 1 }
	return c[1], c[2], c[3], c[4]
end

function frameProto:SetVertexColor(r, g, b, a) self._color = { r, g, b, a } end
function frameProto:GetVertexColor()
	local c = self._color or { 1, 1, 1, 1 }
	return c[1], c[2], c[3], c[4]
end

function frameProto:SetPoint(point, rel, relPoint, x, y)
	self._point = { point, rel, relPoint, x, y }
end
function frameProto:GetPoint()
	local p = self._point or { "CENTER", nil, "CENTER", 0, 0 }
	return p[1], p[2], p[3], p[4], p[5]
end
function frameProto:GetNumPoints() return self._point and 1 or 0 end

function frameProto:SetChecked(v) self._checked = v and true or false end
function frameProto:GetChecked() return self._checked and true or false end

function frameProto:SetRotation(r) self._rotation = r end
function frameProto:GetRotation() return self._rotation or 0 end

function frameProto:SetScale(s) self._scale = s end
function frameProto:GetScale() return self._scale or 1 end

-- The options page is a scroll frame now, because it is taller than the canvas
-- the Settings panel hands out on a good many screens. The offset is kept for
-- real (rather than stubbed) so the code that clamps it has a number to work
-- with -- a stub returning the frame made `math.min` throw.
function frameProto:SetScrollChild(child) self._scrollChild = child end
function frameProto:GetScrollChild() return self._scrollChild end
function frameProto:SetVerticalScroll(v) self._vscroll = v end
function frameProto:GetVerticalScroll() return self._vscroll or 0 end

function frameProto:SetEnabled(v) self._enabled = v and true or false end
function frameProto:Enable() self._enabled = true end
function frameProto:Disable() self._enabled = false end
function frameProto:IsEnabled()
	if self._enabled == nil then return true end
	return self._enabled
end

function frameProto:SetValue(v)
	self._value = v
	local fn = self._scripts and self._scripts.OnValueChanged
	if fn then fn(self, v) end
end
function frameProto:GetValue() return self._value or 0 end

function frameProto:SetScript(which, fn) self._scripts[which] = fn end
function frameProto:GetScript(which) return self._scripts[which] end
function frameProto:HookScript(which, fn)
	local prev = self._scripts[which]
	self._scripts[which] = function(...)
		if prev then prev(...) end
		return fn(...)
	end
end

function frameProto:RegisterEvent(event)
	listeners[event] = listeners[event] or {}
	for _, f in ipairs(listeners[event]) do
		if f == self then return end
	end
	table.insert(listeners[event], self)
end

function frameProto:UnregisterEvent(event)
	local list = listeners[event]
	if not list then return end
	for i = #list, 1, -1 do
		if list[i] == self then table.remove(list, i) end
	end
end

function frameProto:UnregisterAllEvents()
	for event in pairs(listeners) do self:UnregisterEvent(event) end
end

function frameProto:GetName() return self._name end
function frameProto:GetParent() return self._parent end
function frameProto:GetWidth() return self._width or 100 end
function frameProto:GetHeight() return self._height or 100 end
function frameProto:GetObjectType() return self._type end

local function newRegion(kind, name, parent)
	local r = setmetatable({}, frameProto)
	r._type = kind
	r._name = name
	r._parent = parent
	r._shown = true
	r._scripts = {}
	if name then _G[name] = r end
	table.insert(allFrames, r)
	return r
end

function frameProto:CreateTexture(name, layer)
	local t = newRegion("Texture", name, self)
	t._layer = layer
	return t
end

function frameProto:CreateFontString(name, layer)
	local fs = newRegion("FontString", name, self)
	fs._layer = layer
	return fs
end

-- Fire a script handler on this frame, if it has one.
function frameProto:Run(which, ...)
	local fn = self._scripts[which]
	if fn then return fn(self, ...) end
end

-- ---------------------------------------------------------------------------
-- Test-facing controls
-- ---------------------------------------------------------------------------

-- Dispatch an event to every frame registered for it.
function M.fire(event, ...)
	local list = listeners[event]
	if not list then return end
	for _, frame in ipairs({ unpack(list) }) do   -- copy: handlers may unregister
		local fn = frame._scripts.OnEvent
		if fn then fn(frame, event, ...) end
	end
end

-- Move the clock forward, running any timers that come due and driving OnUpdate
-- in `step`-sized slices so tickers fire the right number of times.
function M.advance(seconds, step)
	step = step or 0.05
	local target = clock + seconds
	while clock < target do
		local dt = math.min(step, target - clock)
		clock = clock + dt
		for _, entry in ipairs({ unpack(timers) }) do
			if not entry.cancelled and clock >= entry.due then
				if entry.ticker then
					entry.due = entry.due + entry.interval
					entry.fn()
				else
					entry.cancelled = true
					entry.fn()
				end
			end
		end
		for _, frame in ipairs({ unpack(allFrames) }) do
			if frame._shown and frame._scripts.OnUpdate then
				frame._scripts.OnUpdate(frame, dt)
			end
		end
	end
	-- drop finished one-shots so the list doesn't grow without bound
	for i = #timers, 1, -1 do
		if timers[i].cancelled then table.remove(timers, i) end
	end
end

function M.now() return clock end

-- Player position. Call with no args to make position *unavailable* (the
-- Blizzard-took-it-away case); pass `secret = true` to hand back secret values.
function M.setPosition(a, b, z, instanceID, secret)
	if a == nil then
		M.position = nil
		return
	end
	if secret then
		M.position = { M.secret(a), M.secret(b), z or 0, instanceID or 0 }
	else
		M.position = { a, b, z or 0, instanceID or 0 }
	end
end

function M.setFacing(f, secret)
	M.facing = secret and M.secret(f) or f
end

-- ---------------------------------------------------------------------------
-- Auras and casts
--
-- Both are driven the way the client drives them: state changes, then the event
-- that tells addons to go and look. Nothing here hands the addon the answer.
-- ---------------------------------------------------------------------------

-- Put an aura on `unit` and fire UNIT_AURA. `duration` is what the client
-- declares; `expirationTime` follows from the clock.
--
-- opts:
--   filter       "HELPFUL" (default) or "HARMFUL"
--   silent       do not fire UNIT_AURA, so only a poll can find it
--   secret       hand the name and the timings back as secret values
--   startedAgo   backdate the expiry, as if the aura had already been up this
--                long by the time anything looked
function M.applyAura(unit, name, duration, opts)
	opts = opts or {}
	M.auras[unit] = M.auras[unit] or {}

	local expires = clock + (duration or 0) - (opts.startedAgo or 0)
	local entry = {
		name = name,
		duration = duration,
		expirationTime = expires,
		filter = opts.filter or "HELPFUL",
		spellId = 0,
		auraInstanceID = #M.auras[unit] + 1,
	}
	if opts.secret then
		entry.name = M.secret(name)
		entry.duration = M.secret(duration)
		entry.expirationTime = M.secret(expires)
	end

	table.insert(M.auras[unit], entry)
	if not opts.silent then M.fire("UNIT_AURA", unit) end
end

-- Start a channel on `unit` and fire the events the client fires for one. This
-- is how the boss carries the round: a channel that runs for exactly as long as
-- the waves take.
--
-- opts:
--   secret     the event's spell id comes back secret
--   nameless   UnitChannelInfo's name comes back secret too
--   timeless   its start and end times come back secret, leaving nothing usable
--   startedAgo backdate it, as if it had been running before anything looked
function M.startChannel(unit, spellID, duration, opts)
	opts = opts or {}
	local name = opts.name or "Sermon of Ula'Tek"
	local startMS = (clock - (opts.startedAgo or 0)) * 1000
	local endMS = startMS + duration * 1000

	M.channels[unit] = {
		spellID = spellID,
		name = opts.nameless and M.secret(name) or name,
		startMS = opts.timeless and M.secret(startMS) or startMS,
		endMS = opts.timeless and M.secret(endMS) or endMS,
	}

	local castGUID = ("Chan-%s-%d"):format(unit, math.floor(startMS))
	M.fire("UNIT_SPELLCAST_CHANNEL_START", unit, castGUID,
		opts.secret and M.secret(spellID) or spellID)
end

function M.stopChannel(unit, opts)
	opts = opts or {}
	M.channels[unit] = nil
	if not opts.silent then
		M.fire("UNIT_SPELLCAST_CHANNEL_STOP", unit, nil, nil)
	end
end

function M.removeAura(unit, name, opts)
	opts = opts or {}
	local list = M.auras[unit]
	if list then
		for i = #list, 1, -1 do
			local held = list[i].name
			-- A secret name is a table here, so it never compares equal to the
			-- string; reach past it to the value it is standing in for.
			if held == name or (type(held) == "table" and rawget(held, "__value") == name) then
				table.remove(list, i)
			end
		end
	end
	if not opts.silent then M.fire("UNIT_AURA", unit) end
end

-- Start a cast on `unit` and fire UNIT_SPELLCAST_START.
--
-- opts:
--   castGUID   false for a client that hands none over; a string to pin it
--   secret     the event's spell id comes back as a secret value
--   nameless   the cast bar's spell name is secret too, so the cast cannot be
--              identified by any means at all
--   name       what the cast bar says (default: the wave call)
--   timeless   the cast bar's start and end times are secret as well, leaving
--              nothing about the cast that can be used as a key
function M.startCast(unit, spellID, duration, opts)
	opts = opts or {}
	local name = opts.name or "Echo of Ula'tek"
	local startMS = clock * 1000
	local endMS = startMS + duration * 1000
	M.casts[unit] = {
		spellID = spellID,
		startMS = opts.timeless and M.secret(startMS) or startMS,
		endMS = opts.timeless and M.secret(endMS) or endMS,
		name = opts.nameless and M.secret(name) or name,
	}

	local castGUID = opts.castGUID
	if castGUID == nil then
		castGUID = ("Cast-%s-%d"):format(unit, math.floor(startMS))
	end

	M.fire("UNIT_SPELLCAST_START", unit, castGUID or nil,
		opts.secret and M.secret(spellID) or spellID)
	return castGUID
end

-- ---------------------------------------------------------------------------
-- Install globals
-- ---------------------------------------------------------------------------

function M.reset()
	clock = 1000            -- non-zero: catches code that treats GetTime()==0 as "unset"
	timers = {}
	listeners = {}
	allFrames = {}

	M.spoken = {}
	M.sounds = {}
	M.chat = {}
	M.bindings = {}
	M.popups = {}
	M.position = { 0, 0, 0, 0 }
	M.facing = 0
	M.instanceMapID = 0
	M.zoneText = ""
	M.uiMapID = 0
	M.hostile = {}
	M.guids = {}
	M.auras = {}
	M.casts = {}
	M.channels = {}
	M.aurasBlocked = false

	M.addonMessages = {}    -- { {prefix, text, channel}, ... } sent by the addon
	M.addonPrefixes = {}    -- prefix -> true, once registered
	M.groupSize = 0         -- 0 = solo; the addon only sends when this is > 1
	M.inRaid = false
	M.playerName = "Tester"
	M.playerRealm = "Realm"
	M.groupLeader = nil     -- short name of whoever leads; nil = nobody does
	-- party1..N, realm-qualified the way the client spells them. The addon walks
	-- these to turn a message's sender into a unit token, because a name is not
	-- one -- see the note at the top of Comms.lua's Names section.
	M.groupMembers = { "Caller-Realm", "Someone-Realm", "Third-Realm" }
	M.addonVersion = "1.0.0"

	_G.SnakeSaysDB = nil
	_G.DBM = nil            -- put there by M.installDBM, for the tests that want it

	_G.UIParent = newRegion("Frame", "UIParent", nil)

	-- Templates the live client really ships, and the only ones CreateFrame will
	-- accept here.
	--
	-- The client throws on a template name it does not know, and a mock that
	-- accepts any string cannot see that happen. It is how the voice picker
	-- shipped broken: the options page asked for "WowStyleDropdownTemplate" when
	-- the real one is "WowStyle1DropdownTemplate", CreateFrame threw, the guard
	-- around it caught the error, and the page quietly announced that the client
	-- had no picker -- on a client with two voices installed and a picker.
	--
	-- Add a name here when the addon starts using it, having checked the client
	-- really has it. That check is the point of the list.
	local KNOWN_TEMPLATES = {
		UIPanelButtonTemplate = true,
		UICheckButtonTemplate = true,
		UIRadioButtonTemplate = true,
		OptionsSliderTemplate = true,
		WowStyle1DropdownTemplate = true,
	}

	_G.CreateFrame = function(kind, name, parent, template)
		if template ~= nil and not KNOWN_TEMPLATES[template] then
			error(("CreateFrame: unknown template %q"):format(tostring(template)), 2)
		end
		local f = newRegion(kind or "Frame", name, parent)
		f._template = template
		f._shown = true
		return f
	end

	_G.GameTooltip = newRegion("GameTooltip", "GameTooltip", nil)
	_G.GameTooltip.SetOwner = function() end
	_G.GameTooltip.AddLine = function() end
	_G.GameTooltip.AddDoubleLine = function() end

	_G.GetTime = function() return clock end

	_G.C_Timer = {
		After = function(delay, fn)
			table.insert(timers, { due = clock + delay, fn = fn })
		end,
		NewTimer = function(delay, fn)
			local entry = { due = clock + delay, fn = fn }
			table.insert(timers, entry)
			return {
				Cancel = function() entry.cancelled = true end,
				IsCancelled = function() return entry.cancelled == true end,
			}
		end,
		NewTicker = function(interval, fn)
			local entry = { due = clock + interval, interval = interval, fn = fn, ticker = true }
			table.insert(timers, entry)
			return {
				Cancel = function() entry.cancelled = true end,
				IsCancelled = function() return entry.cancelled == true end,
			}
		end,
	}

	_G.UnitPosition = function(unit)
		if unit ~= "player" or not M.position then return nil end
		return M.position[1], M.position[2], M.position[3], M.position[4]
	end

	_G.GetPlayerFacing = function() return M.facing end

	_G.GetInstanceInfo = function()
		return M.zoneText, "party", 0, "", 0, 0, false, M.instanceMapID
	end

	_G.GetZoneText = function() return M.zoneText end

	_G.UnitCanAttack = function(_, unit) return M.hostile[unit] and true or false end
	_G.UnitExists = function(unit) return M.hostile[unit] ~= nil end
	_G.UnitGUID = function(unit) return M.guids[unit] end

	-- ---------------------------------------------------------------------
	-- Group + addon channel
	-- ---------------------------------------------------------------------

	local function shortOf(name)
		if name == "player" then return M.playerName end
		return tostring(name):match("^[^-]+") or tostring(name)
	end

	-- Which character a unit token stands for, realm and all, or nil for a token
	-- nobody is behind. Deliberately strict about *tokens*: handing this a bare
	-- name gets nothing back, which is what the client does and the whole reason
	-- Comms walks the roster instead of guessing.
	local function memberOf(unit)
		if unit == "player" then return M.playerName, M.playerRealm end
		local index = tostring(unit):match("^party(%d+)$") or tostring(unit):match("^raid(%d+)$")
		if not index then return nil end
		local full = M.groupMembers[tonumber(index)]
		if not full then return nil end
		local name, realm = full:match("^([^-]+)%-?(.*)$")
		return name, (realm ~= "" and realm or nil)
	end

	_G.UnitName = function(unit) return shortOf(unit) end
	_G.UnitFullName = function(unit) return memberOf(unit) end
	-- Faithful to what the live client did, which is not what you would guess:
	-- a realm-qualified name is not a unit token, and does not even resolve the
	-- character you are playing. Observed in the field as
	-- `UnitIsUnit("Genji-Anasterian", "player") -> false`. Anything in the addon
	-- that leans on a name-as-token has to fail here too, or the suite is
	-- agreeing with an assumption the game does not share.
	_G.UnitIsUnit = function(a, b)
		local an = memberOf(a)
		local bn = memberOf(b)
		return an ~= nil and bn ~= nil and an == bn
	end
	_G.Ambiguate = function(name) return shortOf(name) end

	_G.IsInGroup = function() return M.groupSize > 1 end
	_G.IsInRaid = function() return M.inRaid end
	_G.GetNumGroupMembers = function() return M.groupSize end

	-- Answers for real unit tokens only. A name string gets `false`, mirroring
	-- the client behaviour that broke the first cut of this feature.
	_G.UnitIsGroupLeader = function(unit)
		if not M.groupLeader then return false end
		local name = memberOf(unit)
		return name ~= nil and name == M.groupLeader
	end

	_G.C_AddOns = {
		GetAddOnMetadata = function(_, key)
			if key == "Version" then return M.addonVersion end
			return nil
		end,
	}

	_G.C_ChatInfo = {
		RegisterAddonMessagePrefix = function(prefix)
			M.addonPrefixes[prefix] = true
			return true
		end,
		SendAddonMessage = function(prefix, text, channel)
			table.insert(M.addonMessages, { prefix = prefix, text = text, channel = channel })
			return true
		end,
	}

	-- Indexed within a filter, exactly like the client: the addon has to walk it
	-- and stop at the first gap.
	_G.C_UnitAuras = {
		GetAuraDataByIndex = function(unit, index, filter)
			if M.aurasBlocked then
				error("GetAuraDataByIndex(): Auras cannot be accessed when secret while tainted", 2)
			end
			local list = M.auras[unit]
			if not list then return nil end
			local seen = 0
			for _, aura in ipairs(list) do
				if aura.filter == (filter or "HELPFUL") then
					seen = seen + 1
					if seen == index then return aura end
				end
			end
			return nil
		end,
	}

	_G.UnitCastingInfo = function(unit)
		local cast = M.casts[unit]
		if not cast then return nil end
		-- name, text, texture, startTimeMS, endTimeMS, ...
		return cast.name, nil, nil, cast.startMS, cast.endMS
	end

	-- name, text, texture, startTimeMS, endTimeMS, isTradeSkill,
	-- notInterruptible, spellID
	_G.UnitChannelInfo = function(unit)
		local channel = M.channels[unit]
		if not channel then return nil end
		return channel.name, nil, nil, channel.startMS, channel.endMS,
			false, false, channel.spellID
	end

	_G.issecretvalue = isSecret

	_G.C_Map = {
		GetBestMapForUnit = function() return M.uiMapID end,
		GetWorldPosFromMapPos = function() return nil end,
		GetMapArtLayers = function() return nil end,
		GetMapArtLayerTextures = function() return nil end,
	}

	_G.CreateVector2D = function(x, y)
		return { x = x, y = y, GetXY = function(self) return self.x, self.y end }
	end

	_G.C_VoiceChat = {
		GetTtsVoices = function()
			return { { voiceID = 0, name = "Default" }, { voiceID = 1, name = "Alt" } }
		end,
		-- This client's signature, confirmed by ear against the alternative: rate
		-- third, then volume, then overlap. Newer clients grew a `destination`
		-- argument in the rate's slot; this one has no VoiceTtsDestination enum
		-- at all, and speaking with that order is accepted and then silent.
		SpeakText = function(voiceID, text, rate, volume, overlap)
			table.insert(M.spoken, {
				voiceID = voiceID, text = text,
				rate = rate, volume = volume, overlap = overlap,
			})
		end,
	}

	_G.C_TTSSettings = { GetSpeechRate = function() return 0 end }

	_G.Enum = _G.Enum or {}
	_G.Enum.VoiceTtsDestination = {
		LocalPlayback = 0, RemoteTransmission = 1, QueuedLocalPlayback = 2,
	}

	_G.PlaySoundFile = function(file, channel)
		table.insert(M.sounds, { file = file, channel = channel })
		return true, #M.sounds
	end
	_G.PlaySound = function(kit, channel)
		table.insert(M.sounds, { kit = kit, channel = channel })
		return true, #M.sounds
	end
	-- Real SOUNDKIT entries are numeric ids, and the addon type-checks them
	-- before use, so handing back a string here would exercise the wrong branch.
	_G.SOUNDKIT = setmetatable({}, { __index = function(_, k)
		local id = 10000
		for i = 1, #k do id = id + k:byte(i) end
		return id
	end })

	_G.StaticPopupDialogs = {}
	_G.StaticPopup_Show = function(name, ...)
		table.insert(M.popups, name)
		return _G.StaticPopupDialogs[name]
	end
	_G.StaticPopup_Hide = function() end

	_G.Settings = {
		RegisterCanvasLayoutCategory = function(_, name)
			return { GetID = function() return name end, ID = name }
		end,
		RegisterAddOnCategory = function() end,
		OpenToCategory = function() end,
	}

	_G.GetBindingKey = function(command) return M.bindings[command] end
	_G.GetBindingText = function(key) return key end
	_G.SetBinding = function(key, command)
		if command then M.bindings[command] = key
		else
			for c, k in pairs(M.bindings) do
				if k == key then M.bindings[c] = nil end
			end
		end
		return true
	end
	_G.SetBindingClick = function(key, name, button)
		M.bindings["CLICK " .. name .. ":" .. (button or "")] = key
		return true
	end
	_G.SaveBindings = function() end
	_G.GetCurrentBindingSet = function() return 1 end

	-- Macros the addon writes for the player. Character macros only, and capped
	-- the way the client caps them, so "no room left" is reachable in a test.
	M.macros = {}
	M.macroLimit = 30

	-- The macro API takes a file ID, not a path -- a path string is accepted and
	-- then quietly ignored, which is how the first cut produced five macros with
	-- no icon on them. Deterministic here so a test can name the one it wants.
	M.fileIDs = {}
	local nextFileID = 4000000
	_G.GetFileIDFromPath = function(path)
		if not M.fileIDs[path] then
			nextFileID = nextFileID + 1
			M.fileIDs[path] = nextFileID
		end
		return M.fileIDs[path]
	end

	_G.GetMacroIndexByName = function(name)
		for i, m in ipairs(M.macros) do
			if m.name == name then return i end
		end
		return 0
	end
	_G.CreateMacro = function(name, icon, body)
		if #M.macros >= M.macroLimit then return nil end
		table.insert(M.macros, { name = name, icon = icon, body = body })
		return #M.macros
	end
	_G.EditMacro = function(index, name, icon, body)
		local m = M.macros[index]
		if not m then return nil end
		m.name, m.icon, m.body = name, icon, body
		return index
	end

	_G.SlashCmdList = {}

	_G.IsAltKeyDown = function() return false end
	_G.IsControlKeyDown = function() return false end
	_G.IsShiftKeyDown = function() return false end
	_G.IsMouseButtonDown = function() return false end
	_G.InCombatLockdown = function() return false end

	_G.print = function(...)
		local parts = {}
		for i = 1, select("#", ...) do
			parts[i] = tostring((select(i, ...)))
		end
		table.insert(M.chat, table.concat(parts, " "))
	end

	_G.wipe = function(t)
		for k in pairs(t) do t[k] = nil end
		return t
	end
	_G.strtrim = function(s) return (tostring(s):gsub("^%s*(.-)%s*$", "%1")) end
	_G.strsplit = function(sep, s)
		local out = {}
		for piece in tostring(s):gmatch("[^" .. sep .. "]+") do table.insert(out, piece) end
		return unpack(out)
	end
	_G.strlower = string.lower
	_G.format = string.format
	_G.tinsert = table.insert
	_G.tremove = table.remove

	-- Lua 5.1 has math.atan2; 5.2+ dropped it. The addon relies on it.
	if not math.atan2 then
		math.atan2 = function(y, x) return math.atan(y, x) end
	end
end

-- ---------------------------------------------------------------------------
-- Deadly Boss Mods
--
-- Absent by default (M.reset clears it), because most of the suite is about a
-- client that does not have it and the addon has to work there. Installed on
-- request with only the three things Announce reads: which voice pack is
-- chosen, which ones are really there, and the call that plays a file.
--
-- opts:
--   pack      the chosen pack, "None" for a player who turned the voice off
--             (default "VEM")
--   versions  the packs DBM found at login; pass {} for a pack that is named in
--             the settings but no longer installed
-- ---------------------------------------------------------------------------

function M.installDBM(opts)
	opts = opts or {}
	local pack = opts.pack
	if pack == nil then pack = "VEM" end

	_G.DBM = {
		Options = { ChosenVoicePack2 = pack },
		VoiceVersions = opts.versions or { [pack] = 20 },
		PlaySoundFile = function(_, path)
			table.insert(M.sounds, { file = path, channel = "DBM" })
		end,
	}
	return _G.DBM
end

-- The paths of every sound played so far, in order.
function M.soundFiles()
	local out = {}
	for _, entry in ipairs(M.sounds) do out[#out + 1] = entry.file end
	return out
end

-- Run a slash command the way the chat frame would: `M.slash("SNAKESAYS", "hide")`.
function M.slash(handlerKey, args)
	local handler = _G.SlashCmdList[handlerKey]
	assert(handler, "no slash handler registered for " .. tostring(handlerKey))
	return handler(args or "")
end

-- Deliver an addon message the way the client would, from somebody else.
-- `sender` arrives realm-qualified, always, which is what the addon has to cope
-- with when it works out whether a message is its own coming back.
function M.addonMessage(prefix, text, sender, channel)
	M.fire("CHAT_MSG_ADDON", prefix, text, channel or "PARTY", sender or "Caller-Realm")
end

-- The bodies of every addon message the addon has sent, in order.
function M.sentAddonMessages()
	local out = {}
	for i, msg in ipairs(M.addonMessages) do out[i] = msg.text end
	return out
end

-- Did the mock ever hand out a chat line containing `needle`?
function M.chatContains(needle)
	for _, line in ipairs(M.chat) do
		if line:find(needle, 1, true) then return true end
	end
	return false
end

-- Everything spoken so far, as plain strings.
function M.spokenText()
	local out = {}
	for i, entry in ipairs(M.spoken) do out[i] = entry.text end
	return out
end

return M
