-- Phase 4: what the player hears and reads during the silent replay --
-- the voice call, the bell that confirms they made it, and the on-screen popup.

local wow = require("spec.helpers.wow")
local enc = require("spec.helpers.encounter")

-- Default assignment: N = Circle (orange), E = Diamond (purple),
-- S = Square (blue), W = Cross (red).
local RUN = { "W", "N", "S" }          -- Red, Orange, Blue

describe("voice calls", function()
	it("speaks the safe colour at each step of the replay", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns); enc.echo(ns); enc.echo(ns)
		assert.same({ "Red", "Orange", "Blue" }, wow.spokenText())
	end)

	it("says nothing while the run is still being recorded", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		assert.equals(0, #wow.spoken)
	end)

	it("can announce marker names instead of colours", function()
		local ns = enc.setup("auto", { announceStyle = "marker" })
		enc.recordRun(ns, RUN)
		enc.echo(ns); enc.echo(ns); enc.echo(ns)
		assert.same({ "Cross", "Circle", "Square" }, wow.spokenText())
	end)

	it("follows a reassigned marker", function()
		local ns = enc.setup("auto")
		ns.SetAssignment("W", 4)         -- West becomes Triangle (green)
		enc.recordRun(ns, { "W" , "N", "S" })
		enc.echo(ns)
		assert.equals("Green", wow.spokenText()[1])
	end)

	it("stays silent when text to speech is switched off", function()
		local ns = enc.setup("auto", { ttsEnabled = false })
		enc.recordRun(ns, RUN)
		enc.echo(ns); enc.echo(ns)
		assert.equals(0, #wow.spoken)
	end)

	it("passes rate, volume and overlap the way the client expects", function()
		local ns = enc.setup("auto", { ttsVolume = 80, ttsOverlap = false })
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		local call = wow.spoken[1]
		assert.equals(80, call.volume)
		assert.equals(false, call.overlap)
		assert.equals(0, call.rate)
	end)

	it("falls back to the default voice when the stored one is gone", function()
		local ns = enc.setup("auto", { ttsVoice = 77 })   -- not in GetTtsVoices()
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.equals(0, wow.spoken[1].voiceID)
	end)

	it("keeps a stored voice that still exists", function()
		local ns = enc.setup("auto", { ttsVoice = 1 })
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.equals(1, wow.spoken[1].voiceID)
	end)
end)

describe("safe-arrival bell", function()
	local function stepInto(ns, quadrant, seconds)
		enc.placeIn(ns, quadrant)
		wow.advance(seconds or 0.5)
	end

	it("rings once the player reaches the safe quadrant", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "N")             -- wrong quadrant for step 1 (W is safe)
		enc.echo(ns)
		assert.equals(0, #wow.sounds)

		stepInto(ns, "W")
		assert.equals(1, #wow.sounds)
	end)

	it("rings only once per step, however much the player shuffles", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "N")
		enc.echo(ns)

		stepInto(ns, "W")
		stepInto(ns, "N")
		stepInto(ns, "W")
		assert.equals(1, #wow.sounds)
	end)

	it("rings again on the next step", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "N")
		enc.echo(ns)
		stepInto(ns, "W")
		assert.equals(1, #wow.sounds)

		enc.echo(ns)                     -- step 2, safe quadrant is N
		stepInto(ns, "N")
		assert.equals(2, #wow.sounds)
	end)

	it("rings immediately when the player is already standing safe", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "W")             -- already in the safe spot for step 1
		enc.echo(ns)
		wow.advance(0.5)
		assert.equals(1, #wow.sounds)
	end)

	it("does not ring outside the replay", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		wow.advance(2)
		assert.equals(0, #wow.sounds)
	end)

	it("stays silent when the bell is switched off", function()
		local ns = enc.setup("auto", { bellEnabled = false })
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "N")
		enc.echo(ns)
		stepInto(ns, "W")
		assert.equals(0, #wow.sounds)
	end)

	it("does not ring when position cannot be read", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.placeIn(ns, "N")
		enc.echo(ns)
		wow.setPosition(nil)
		wow.advance(1)
		assert.equals(0, #wow.sounds)
	end)
end)

describe("next-up popup", function()
	it("shows the current colour large and the next one as a subtitle", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns)

		assert.is_true(ns.Announce.IsPopupShown())
		assert.is_true(ns.Announce.PopupText():find("Red", 1, true) ~= nil)
		assert.is_true(ns.Announce.PopupSubtitle():find("Orange", 1, true) ~= nil)
		assert.is_true(ns.Announce.PopupSubtitle():find("next", 1, true) ~= nil)
	end)

	it("includes the marker icon alongside the word", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.is_true(ns.Announce.PopupText():find("|T", 1, true) ~= nil)
	end)

	it("drops the subtitle on the final wave, where there is no next", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns); enc.echo(ns); enc.echo(ns)
		assert.is_true(ns.Announce.PopupText():find("Blue", 1, true) ~= nil)
		assert.equals("", ns.Announce.PopupSubtitle())
	end)

	it("hides the subtitle when that setting is off, keeping the main line", function()
		local ns = enc.setup("auto", { popupSubtitle = false })
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.is_true(ns.Announce.PopupText():find("Red", 1, true) ~= nil)
		assert.equals("", ns.Announce.PopupSubtitle())
	end)

	it("uses marker names when that style is selected", function()
		local ns = enc.setup("auto", { announceStyle = "marker" })
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.is_true(ns.Announce.PopupText():find("Cross", 1, true) ~= nil)
		assert.is_true(ns.Announce.PopupSubtitle():find("Circle", 1, true) ~= nil)
	end)

	it("stays hidden when the popup is switched off", function()
		local ns = enc.setup("auto", { popupEnabled = false })
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		assert.is_false(ns.Announce.IsPopupShown())
	end)

	it("hides itself once the replay is over", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns); enc.echo(ns); enc.echo(ns)
		assert.is_true(ns.Announce.IsPopupShown())
		wow.advance(15)                  -- past the replay linger
		assert.is_false(ns.Announce.IsPopupShown())
	end)

	it("hides when the encounter ends mid-replay", function()
		local ns = enc.setup("auto")
		enc.recordRun(ns, RUN)
		enc.echo(ns)
		wow.fire("ENCOUNTER_END", ns.ENCOUNTERS[1].id)
		assert.is_false(ns.Announce.IsPopupShown())
	end)

	it("remembers a position the player dragged it to", function()
		local ns = enc.setup("auto")
		ns.Announce.SavePopupPosition("TOP", "TOP", 12, -300)
		assert.same({ point = "TOP", relPoint = "TOP", x = 12, y = -300 },
			_G.SnakeSaysDB.popupPosition)
	end)
end)

describe("announce settings", function()
	it("defaults to speaking colours, with popup, subtitle and bell on", function()
		local ns = enc.setup("auto")
		assert.is_true(ns.GetTTSEnabled())
		assert.equals("color", ns.GetAnnounceStyle())
		assert.is_true(ns.GetPopupEnabled())
		assert.is_true(ns.GetPopupSubtitle())
		assert.is_true(ns.GetBellEnabled())
	end)

	it("round-trips every toggle through SavedVariables", function()
		local ns = enc.setup("auto")
		ns.SetTTSEnabled(false)
		ns.SetAnnounceStyle("marker")
		ns.SetPopupEnabled(false)
		ns.SetPopupSubtitle(false)
		ns.SetBellEnabled(false)

		assert.is_false(_G.SnakeSaysDB.ttsEnabled)
		assert.equals("marker", _G.SnakeSaysDB.announceStyle)
		assert.is_false(_G.SnakeSaysDB.popupEnabled)
		assert.is_false(_G.SnakeSaysDB.popupSubtitle)
		assert.is_false(_G.SnakeSaysDB.bellEnabled)
	end)

	it("ignores an announce style it does not know", function()
		local ns = enc.setup("auto")
		ns.SetAnnounceStyle("interpretive dance")
		assert.equals("color", ns.GetAnnounceStyle())
	end)
end)
